Add support for rotating service account in Datadog's GCP integration
ovotech/cloud-key-rotator pull request #301
Opened 2021-01-29 17:21 UTC by chris-brindley

This PR adds a new location, `DatadogGCPIntegration`, that allows rotating of the service account key that is used for the Datadog GCP integration.

Hopefully the code is fairly self explanatory. The API documentation for the Datadog GCP integration can be found [here](https://docs.datadoghq.com/api/latest/gcp-integration/) for reference. The location attempts to retrieve the existing integration from the Datadog API before adding the newly generated keys to it, and will fail if the existing integration could not be found.

At this point I haven't done any refactoring of the existing code surrounding Datadog's metrics submission, but I think it will probably be worthwhile to do so, maybe in a separate PR, so the Datadog API key only needs to be included in the config once.

Was unsure about testing in this project. There doesn't seem to be much done for locations?

2021-02-03 20:09 UTC, eversC requested changes
Looks great Chris, thanks for spending the time on it.

The only request I have for change is could we please have this new integration added to the lists of locations in the readme in project root? There are actually two lists there; one at the top and another further down where locations are covered in more detail.

In terms of the testing of locations, it's not ideal that we don't yet have any, but mocks would make a great addition/issue to work on, maybe we can pair on it?

I raised https://github.com/ovotech/cloud-key-rotator/issues/305

2021-02-03 20:12 UTC, eversC commented
Oh, also, did you manage to do any dev testing with a real service-account/key/ddog integration?

2021-02-04 09:27 UTC, chris-brindley commented
Readme updated as requested.

I did test it out with a real service account and real Datadog integration during and after development. It seemed to work exactly as anticipated - metrics and logs continued to be reported after rotation.

2021-02-05 19:03 UTC, eversC approved these changes

2021-02-05 19:03 UTC, merged